version: "3.8" #
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thedarkside
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ccabnalp@miumg.edu.gt
      PGADMIN_DEFAULT_PASSWORD: sistemas
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: